### ISSUE TITLE
About Assignment #1: DECIDE.

### ISSUE THREAD

**Issue by fermadeiral** [soffgrupp6/assignment1#64]
Hi, everyone.

You should post the repository URL of your project on Canvas!

The final deadline is tonight. I will be analyzing your repository after that. Read carefully again the table about grading (https://kth.instructure.com/courses/22002/assignments/137591). For instance, make sure that the commits are well balanced among group members.

Best,
Fernanda

**Comment by fermadeiral** [comment]
Additional comment: if the group aims P+, clearly state in the README the "remarkable" achievement(s).

**Comment by christian-stj** [comment]
@fermadeiral In the grading instruction, it says only one of the points must be achieved for P+. We have gone for making every commit link to an issue and we have done so since our presentation on Wednesday.

**Comment by fermadeiral** [comment]
> @fermadeiral In the grading instruction, it says only one of the points must be achieved for P+

That's right, which is why you should add that on the README of your repository so I can know how to evaluate if you get a P+ or not.

Since you mentioned the grading instruction, note the following:

"Property: most commits (typically 90%) are linked to an issue describing the feature / commit.
Assessment: The grader will open a random sample of commits and assess  whether they point to a valid issue. The grader will open a random  sample of issues and assess whether they clearly describe (and  optionally discuss) a feature or problem (for bugs)."

Which means that most commits should be linked to an issue, and the issue also needs to be well-described.

> We have gone for making every commit link to an issue

I'm not sure that this is correct. I took a quick look in the history of the master branch and very few commits are linked to issues.

**Comment by it4e** [comment]
@fermadeiral 

We have linked them on Github, it is not in the commit message itself. If you look at the pull requests in Github you will see that they all are linked to an issue.

**Comment by fermadeiral** [comment]
> If you look at the pull requests in Github you will see that they all are linked to an issue.

This is correct. But, see, you linked PRs to issues, not commits. I asked this to Cyrille to be sure how this situation should be evaluated, and I sent a message to all groups (including yours) on Canvas with clarifications, and one of them was that.

If you guys want to try P+, you should try to fix the history of your project (be very, very careful!), or go with something else that can be considerable remarkable achievement that you are proud of.

And, please, like I already asked in the first message of this issue, post the repository URL of your project on Canvas, because so far I see "This group does not have a submission for this assignment".

**Comment by fermadeiral** [comment]
Thank you for addressing this issue. I can already see the repository URL on Canvas.

About the P+, I also see that you added something in the README. That is fine. Here I will give you other suggestions that I thought you would have mentioned, because are very good things:

- The usage of milestones
- The fact that most of issues were assigned to someone (which means that the work was clearly divided and communicated to all members)
- The fact that several PRs (maybe all) were approved/merged by a different person than their authors (which shows collaboration)

For next time: please, use English in the PR comments.

I will be analyzing your repository for the last time after the final deadline tonight!

Good luck!
